spring:
  application:
    name: ibm-mq-spring-listener
#  autoconfigure:
#    exclude[0]: org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
#    exclude[1]: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
#    exclude[2]: org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration
#    exclude[3]: org.springframework.boot.autoconfigure.data.web.SpringDataWebAutoConfiguration
#    exclude[4]: org.springframework.boot.autoconfigure.data.jpa.JpaRepositoriesAutoConfiguration

server:
  port: 1515
  tomcat:
    use-relative-redirects: true

ibm:
  mq:
    queueManager: QM1
    channel: DEV.ADMIN.SVRCONN
    connName: localhost(1414)
    user: admin
    password: passw0rd

servers:
  mq:
    user: admin
    password: passw0rd
    hostName: 127.0.0.1
    port: 1414
    queueManager: QM1
    channel: DEV.ADMIN.SVRCONN
    queue: ONE.QUEUE
    topic: ONE/TOPIC
    timeout: 2000
    clientId: subscriber1
    clientId2: subscriber2
    topic1: DEV.QUEUE.1
    topic2: DEV.QUEUE.2
